name: "Release Notes from Commit Messages"
description: "Generate release notes from commit messages"
author: "Viachaslau Lyskouski"
branding:
  icon: "anchor"
  color: "orange"

inputs:
  version:
    description: "The version of the release"
    required: true
    default: "1.0.0"

outputs:
  release_notes:
    description: "Release notes"
    value: ${{ steps.prepare_release_notes.outputs.release_notes }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare Release Notes
      id: prepare_release_notes
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/gen-release.sh
        RELEASE_NOTES=$($GITHUB_ACTION_PATH/gen-release.sh v${{ inputs.version }})
        echo "release_notes<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT